global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Weather MCP Service
  - job_name: 'clima-mcp'
    static_configs:
      - targets: ['clima-mcp:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (System metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (Container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Custom health endpoints
  - job_name: 'clima-mcp-health'
    static_configs:
      - targets: ['clima-mcp:8000']
    metrics_path: /health
    scrape_interval: 30s
